## Uncaught Asynchronous Exception in Extension Code

Uncaught asynchronous exceptions thrown by extension code require careful consideration. Such exceptions lead to the termination of the process in which the extension is running. Depending on the isolation scope you have selected, there may be other extensions executing in that process at the same time. For example, if a single tenant defined multiple extensions, and there are multiple concurrent transactions of that tenant which require execution of extensions, an uncaught exception generated by one execution will termite the execution of all other concurrently executing extensions in the same process. Given that, if you receive the "Uncaught asynchronous exception" error, it may as well indicate a problem in the code or exection of another extension. 

This is an extension that generates an uncaught asynchronous exception:

```javascript
module.exports = (ctx, cb) => {
  setTimeout(() => {
    throw new Error('Some error');
  }, 1000);
};
```

Response: 

```
HTTP/1.1 500 Internal Server Error
Content-type: application/json
x-wt-response-source: webtask

{
  "code": 500,
  "error": "Script generated an unhandled asynchronous exception.",
  "details": "Error: Some error",
  "name": "Error",
  "message": "Some error",
  "stack": "..."
}
```